resource_group_name="vpc-subnets-rg"
region="us-east"
name_prefix="vpc-subnets"
vpc_subnet_count="0"
vpc_subnets="[{\"label\":\"default\"},{\"label\":\"default\"},{\"label\":\"test\"},{\"label\":\"cluster\"},{\"label\":\"cluster\"}]"
vpc_public_gateway="true"
vpc_subnet_label="cluster"
cluster_exists="false"
